package com.model;

public enum DistrictEnum {

    AGRA, MATHURA, FIROZABAD, MAINPURI, ETAH, HATHRAS, ALIGARH, KASGANJ, ALLAHABAD, FATEHPUR, PRATAPGARH, KAUSHAMBHI, AZAMGARH, MAU, BALLIA, BAREILLY, BADAUN, SHAHJAHANPUR, PILIBHIT, BASTI, SIDHARTH_NAGAR, S_K_NAGAR, HAMIRPUR, MAHOBA, BANDA, CHITRAKOOT, AMETHI, FAIZABAD, SULTANPUR, BARABANKI, AMBEDKAR_NAGAR, GONDA, BAHRAICH, BALRAMPUR, SHRAWASTI, GORAKHPUR, MAHRAJGANJ, DEORIA, KUSHINAGAR, JHANSI, LALITPUR, JALUAN, KANPUR_NAGAR, KANPUR_DEHAT, ETAWAH, FARRUKHABAD, KANNAUJ, AURIYA, LUCKNOW, UNNAO, RAIBAREILI, SITAPUR, HARDOI, LAKHIMPUR_KHIRI, HAPUR, MEERUT, GHAZIABAD, BULANDSHAHAR, G_B_NAGAR, BAGHPAT, MIRZAPUR, SONEBHADRA, S_R_NAGAR, SAMBHAL, MORADABAD, RAMPUR, BIJNOR, AMROHA, SAHARANPUR, MUZAFFARNAGAR, SHAMLI, VARANASI, JAUNPUR, GHAZIPUR, CHANDAULI
}
