package com.model;

public enum MandalEnum {
    AGRA, ALIGARH, ALLAHABAD, AZAMGARH, BAREILLY, BASTI, CHITRAKOOT, FAIZABAD, GONDA, GORAKHPUR, JHANSI, KANPUR, LUCKNOW, MEERUT, MIRZAPUR, MORADABAD, SAHARANPUR, VARANASI
}
